name: rv1g_info
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.4+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  supabase: ^1.9.5
  supabase_flutter: ^1.10.9
  dbcrypt: ^2.0.0
  
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  camera: ^0.10.5+4
  google_mlkit_text_recognition: ^0.10.0

  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  the_validator: ^2.0.0
  image_picker: ^1.0.4
  permission_handler: ^10.4.3
  styled_text: ^8.1.0
  url_launcher: ^6.1.12
  flutter_slidable: ^3.0.0
  flutter_polls: ^0.1.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  rename: ^2.1.1
  flutter_native_splash: ^2.3.2

  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/rv1g_info_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/rv1g_info_logo_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/rv1g_splash_screen.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/Instagram_icon.png
    - assets/2021_Facebook_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
