// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiX3lGQCSgNQRaE_6yZoj7PUwgzhsP0_M',
    appId: '1:612731394663:android:98e831470a1bbee59452c2',
    messagingSenderId: '612731394663',
    projectId: 'rv1g-info',
    databaseURL: 'https://rv1g-info-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rv1g-info.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGf5H3DmZuaHuk64W7e4xc1jp6iD3vTwQ',
    appId: '1:612731394663:ios:309d66e7eb87cacb9452c2',
    messagingSenderId: '612731394663',
    projectId: 'rv1g-info',
    databaseURL: 'https://rv1g-info-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rv1g-info.appspot.com',
    iosClientId: '612731394663-5uueltef7tsrbocvulesopf7luilhmaf.apps.googleusercontent.com',
    iosBundleId: 'com.rv1g.info.rv1gInfoo',
  );
}
